### ISSUE TITLE
Feature Request: missing insert/remove index APIs?

### ISSUE THREAD

**Issue by linrongbin16** [brurucy/ftree#5]
Hi, after read the document: https://docs.rs/ftree/latest/ftree/struct.FenwickTree.html#.

I found there's no APIs to allow user insert/remove new indexes, or say, the Fenwick tree doesn't allow user the change the length.

Can we add this feature?

**Comment by brurucy** [comment]
It is possible to push and pop with O(log (n)) complexity, but unfortunately the Fenwick Tree cannot "insert at index" or "delete at index" efficiently (faster than O(n)).

I will add `push` and `pop`.

**Comment by linrongbin16** [comment]
Thank you!

**Comment by brurucy** [comment]
Done. `ftree` now has `push` and `pop` methods.
